"""add feedback column to queries

Revision ID: 076d9c2a5124
Revises: e8fe99e48ff8
Create Date: 2025-11-11 09:38:14.405592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '076d9c2a5124'
down_revision: Union[str, Sequence[str], None] = 'e8fe99e48ff8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queries', sa.Column('feedback', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('queries', 'feedback')
    # ### end Alembic commands ###
