"""initial migration

Revision ID: e72505336386
Revises: 
Create Date: 2025-11-17 01:42:28.826627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e72505336386'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'metadata')
    op.add_column('queries', sa.Column('normalized_query', sa.String(), nullable=True))
    op.create_index(op.f('ix_queries_normalized_query'), 'queries', ['normalized_query'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_queries_normalized_query'), table_name='queries')
    op.drop_column('queries', 'normalized_query')
    op.add_column('documents', sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
