"""add rating column to queries

Revision ID: e8fe99e48ff8
Revises: 9005fda2a59b
Create Date: 2025-11-10 15:06:26.017209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8fe99e48ff8'
down_revision: Union[str, Sequence[str], None] = '9005fda2a59b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queries', sa.Column('rating', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('queries', 'rating')
    # ### end Alembic commands ###
